-- ============================================================================
-- VIAJOU — Schema para H2 local (modo PostgreSQL). Fase 1 da migração Supabase → H2.
-- Traduzido de supabase/migrations/20260929000001_schema.sql. Diferenças de dialeto:
--  * enums viram VARCHAR + CHECK; text vira VARCHAR(n) (TEXT no H2 é CLOB);
--  * DEFAULT vem antes de PRIMARY KEY; updated_at usa ON UPDATE CURRENT_TIMESTAMP;
--  * sem RLS, triggers PL/pgSQL e RPCs: essas regras vão para lib/db (Fase 2+);
--  * search_key guarda o nome sem acento (calculado pela aplicação) para a busca.
-- ============================================================================

-- Contas -------------------------------------------------------------------
CREATE TABLE users (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sessions (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX sessions_user_idx ON sessions (user_id);

CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  username VARCHAR(30) NOT NULL UNIQUE CHECK (REGEXP_LIKE(username, '^[a-z0-9_]{3,30}$')),
  full_name VARCHAR(80) NOT NULL CHECK (CHAR_LENGTH(full_name) >= 1),
  bio VARCHAR(300),
  avatar_url VARCHAR(500),
  search_key VARCHAR(200),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- Destinos e lugares --------------------------------------------------------
CREATE TABLE destinations (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  slug VARCHAR(120) NOT NULL UNIQUE CHECK (REGEXP_LIKE(slug, '^[a-z0-9]+(-[a-z0-9]+)*$')),
  name VARCHAR(120) NOT NULL,
  city VARCHAR(120) NOT NULL,
  state VARCHAR(60) NOT NULL,
  country VARCHAR(80) DEFAULT 'Brasil' NOT NULL,
  description VARCHAR(2000),
  latitude NUMERIC(9, 6) CHECK (latitude BETWEEN -90 AND 90),
  longitude NUMERIC(9, 6) CHECK (longitude BETWEEN -180 AND 180),
  cover_url VARCHAR(500),
  is_demo BOOLEAN DEFAULT FALSE NOT NULL,
  search_key VARCHAR(400),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE places (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  destination_id UUID REFERENCES destinations (id) ON DELETE SET NULL,
  slug VARCHAR(160) NOT NULL UNIQUE CHECK (REGEXP_LIKE(slug, '^[a-z0-9]+(-[a-z0-9]+)*$')),
  name VARCHAR(160) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('hotel', 'restaurant', 'beach', 'attraction', 'tour', 'other')),
  description VARCHAR(2000),
  address VARCHAR(300),
  city VARCHAR(120),
  state VARCHAR(60),
  country VARCHAR(80) DEFAULT 'Brasil',
  latitude NUMERIC(9, 6) CHECK (latitude BETWEEN -90 AND 90),
  longitude NUMERIC(9, 6) CHECK (longitude BETWEEN -180 AND 180),
  image_url VARCHAR(500),
  website VARCHAR(300),
  phone VARCHAR(40),
  rating_avg NUMERIC(3, 2) DEFAULT 0 NOT NULL,
  reviews_count INTEGER DEFAULT 0 NOT NULL,
  is_demo BOOLEAN DEFAULT FALSE NOT NULL,
  search_key VARCHAR(400),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX places_destination_idx ON places (destination_id, type);
CREATE INDEX places_rating_idx ON places (rating_avg DESC, reviews_count DESC);

-- Critérios de avaliação ("key" é palavra reservada no H2: sempre entre aspas).
CREATE TABLE review_categories (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" VARCHAR(40) NOT NULL UNIQUE,
  label VARCHAR(60) NOT NULL
);

CREATE TABLE place_categories (
  place_type VARCHAR(20) NOT NULL CHECK (place_type IN ('hotel', 'restaurant', 'beach', 'attraction', 'tour', 'other')),
  review_category_id SMALLINT NOT NULL REFERENCES review_categories (id) ON DELETE CASCADE,
  position SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (place_type, review_category_id)
);

-- Avaliações (uma por usuário por lugar) --------------------------------------
CREATE TABLE reviews (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  place_id UUID NOT NULL REFERENCES places (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title VARCHAR(120),
  body VARCHAR(3000) NOT NULL CHECK (CHAR_LENGTH(body) >= 10),
  visited_on DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  UNIQUE (place_id, user_id)
);
CREATE INDEX reviews_place_idx ON reviews (place_id, created_at DESC);
CREATE INDEX reviews_user_idx ON reviews (user_id, created_at DESC);

CREATE TABLE review_category_scores (
  review_id UUID NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
  category_id SMALLINT NOT NULL REFERENCES review_categories (id) ON DELETE CASCADE,
  score SMALLINT NOT NULL CHECK (score BETWEEN 1 AND 5),
  PRIMARY KEY (review_id, category_id)
);

-- Nota agregada por destino (média das avaliações dos seus lugares).
CREATE VIEW destination_stats AS
SELECT d.id AS destination_id,
       CAST(COUNT(r.id) AS INTEGER) AS reviews_count,
       COALESCE(ROUND(AVG(CAST(r.rating AS NUMERIC(5, 2))), 2), 0) AS rating_avg
  FROM destinations d
  LEFT JOIN places p ON p.destination_id = d.id
  LEFT JOIN reviews r ON r.place_id = p.id
 GROUP BY d.id;

-- Publicações ---------------------------------------------------------------
CREATE TABLE posts (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  destination_id UUID REFERENCES destinations (id) ON DELETE SET NULL,
  hotel_place_id UUID REFERENCES places (id) ON DELETE SET NULL,
  body VARCHAR(5000) NOT NULL CHECK (CHAR_LENGTH(body) >= 10),
  trip_start DATE,
  trip_end DATE,
  spent_cents INTEGER CHECK (spent_cents >= 0),
  rating SMALLINT CHECK (rating BETWEEN 1 AND 5),
  tags VARCHAR(40) ARRAY DEFAULT ARRAY[] NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  CHECK (trip_end IS NULL OR trip_start IS NULL OR trip_end >= trip_start)
);
CREATE INDEX posts_feed_idx ON posts (created_at DESC);
CREATE INDEX posts_user_idx ON posts (user_id, created_at DESC);
CREATE INDEX posts_destination_idx ON posts (destination_id, created_at DESC);

CREATE TABLE post_places (
  post_id UUID NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  place_id UUID NOT NULL REFERENCES places (id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, place_id)
);
CREATE INDEX post_places_place_idx ON post_places (place_id);

CREATE TABLE post_photos (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  storage_path VARCHAR(300) NOT NULL UNIQUE,
  alt VARCHAR(200),
  position SMALLINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX post_photos_post_idx ON post_photos (post_id, position);

CREATE TABLE comments (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  post_id UUID NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  parent_id UUID REFERENCES comments (id) ON DELETE CASCADE,
  body VARCHAR(1000) NOT NULL CHECK (CHAR_LENGTH(body) >= 1),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX comments_post_idx ON comments (post_id, created_at);

CREATE TABLE post_likes (
  post_id UUID NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE post_saves (
  post_id UUID NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (post_id, user_id)
);
CREATE INDEX post_saves_user_idx ON post_saves (user_id, created_at DESC);

-- Seguidores ----------------------------------------------------------------
CREATE TABLE follows (
  follower_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (follower_id, following_id),
  CONSTRAINT follows_not_self CHECK (follower_id <> following_id)
);
CREATE INDEX follows_following_idx ON follows (following_id);

-- Roteiros ------------------------------------------------------------------
CREATE TABLE itineraries (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  destination_id UUID REFERENCES destinations (id) ON DELETE SET NULL,
  title VARCHAR(120) NOT NULL CHECK (CHAR_LENGTH(title) >= 3),
  description VARCHAR(2000),
  days_count SMALLINT NOT NULL CHECK (days_count BETWEEN 1 AND 30),
  tags VARCHAR(40) ARRAY DEFAULT ARRAY[] NOT NULL,
  is_public BOOLEAN DEFAULT TRUE NOT NULL,
  copied_from UUID REFERENCES itineraries (id) ON DELETE SET NULL,
  search_key VARCHAR(2200),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX itineraries_public_idx ON itineraries (is_public, created_at DESC);
CREATE INDEX itineraries_destination_idx ON itineraries (destination_id);

CREATE TABLE itinerary_days (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  itinerary_id UUID NOT NULL REFERENCES itineraries (id) ON DELETE CASCADE,
  day_number SMALLINT NOT NULL CHECK (day_number BETWEEN 1 AND 30),
  title VARCHAR(120),
  description VARCHAR(1000),
  UNIQUE (itinerary_id, day_number)
);

CREATE TABLE itinerary_places (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  day_id UUID NOT NULL REFERENCES itinerary_days (id) ON DELETE CASCADE,
  place_id UUID REFERENCES places (id) ON DELETE SET NULL,
  custom_name VARCHAR(120),
  start_time TIME,
  notes VARCHAR(500),
  position SMALLINT DEFAULT 0 NOT NULL,
  CHECK (place_id IS NOT NULL OR custom_name IS NOT NULL)
);
CREATE INDEX itinerary_places_day_idx ON itinerary_places (day_id, position);

CREATE TABLE itinerary_likes (
  itinerary_id UUID NOT NULL REFERENCES itineraries (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (itinerary_id, user_id)
);

CREATE TABLE itinerary_saves (
  itinerary_id UUID NOT NULL REFERENCES itineraries (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (itinerary_id, user_id)
);
CREATE INDEX itinerary_saves_user_idx ON itinerary_saves (user_id, created_at DESC);

-- Estabelecimentos ------------------------------------------------------------
-- Correção da análise inicial: o UNIQUE em place_id deixava um pedido pendente bloquear
-- o lugar para todos. Agora cada usuário pede uma vez por lugar; "só um verificado por
-- lugar" fica na aplicação (lib/db), na hora de verificar.
CREATE TABLE business_profiles (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  place_id UUID REFERENCES places (id) ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL CHECK (CHAR_LENGTH(name) >= 2),
  type VARCHAR(20) NOT NULL CHECK (type IN ('hotel', 'restaurant', 'agency', 'tour', 'attraction')),
  claim_status VARCHAR(20) DEFAULT 'pending' NOT NULL CHECK (claim_status IN ('pending', 'verified', 'rejected')),
  verified_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE (owner_id, place_id)
);
CREATE INDEX business_profiles_place_idx ON business_profiles (place_id, claim_status);

-- Reclamações ---------------------------------------------------------------
CREATE TABLE complaints (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  place_id UUID NOT NULL REFERENCES places (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  category VARCHAR(30) NOT NULL CHECK (category IN ('billing', 'customer_service', 'reservation', 'service', 'cleanliness', 'advertising', 'other')),
  title VARCHAR(120) NOT NULL CHECK (CHAR_LENGTH(title) >= 5),
  description VARCHAR(4000) NOT NULL CHECK (CHAR_LENGTH(description) >= 20),
  status VARCHAR(20) DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'answered', 'resolved', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX complaints_place_idx ON complaints (place_id, created_at DESC);
CREATE INDEX complaints_user_idx ON complaints (user_id, created_at DESC);

CREATE TABLE complaint_photos (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  complaint_id UUID NOT NULL REFERENCES complaints (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  storage_path VARCHAR(300) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE complaint_responses (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  complaint_id UUID NOT NULL REFERENCES complaints (id) ON DELETE CASCADE,
  business_id UUID NOT NULL REFERENCES business_profiles (id) ON DELETE CASCADE,
  responder_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  body VARCHAR(4000) NOT NULL CHECK (CHAR_LENGTH(body) >= 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Planejamento "Vou viajar" ---------------------------------------------------
CREATE TABLE trip_plans (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  destination_id UUID NOT NULL REFERENCES destinations (id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  travelers SMALLINT NOT NULL CHECK (travelers BETWEEN 1 AND 50),
  budget_cents INTEGER CHECK (budget_cents >= 0),
  preferences VARCHAR(40) ARRAY DEFAULT ARRAY[] NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CHECK (end_date >= start_date)
);
CREATE INDEX trip_plans_user_idx ON trip_plans (user_id, created_at DESC);

-- Notificações (criadas pela aplicação, nunca para ações do próprio usuário) ---
CREATE TABLE notifications (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  actor_id UUID REFERENCES profiles (id) ON DELETE CASCADE,
  type VARCHAR(30) NOT NULL CHECK (type IN ('follow', 'post_like', 'comment', 'comment_reply', 'itinerary_saved', 'business_response')),
  post_id UUID REFERENCES posts (id) ON DELETE CASCADE,
  comment_id UUID REFERENCES comments (id) ON DELETE CASCADE,
  itinerary_id UUID REFERENCES itineraries (id) ON DELETE CASCADE,
  complaint_id UUID REFERENCES complaints (id) ON DELETE CASCADE,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CHECK (actor_id IS NULL OR actor_id <> user_id)
);
CREATE INDEX notifications_user_idx ON notifications (user_id, created_at DESC);

-- Denúncias (moderação humana; nada é escondido automaticamente) --------------
CREATE TABLE reports (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  reporter_id UUID NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('post', 'comment', 'review', 'profile', 'photo')),
  target_id UUID NOT NULL,
  reason VARCHAR(30) NOT NULL CHECK (reason IN ('spam', 'offensive', 'false_information', 'fraud', 'inappropriate', 'other')),
  details VARCHAR(1000),
  status VARCHAR(20) DEFAULT 'open' NOT NULL CHECK (status IN ('open', 'reviewing', 'closed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE (reporter_id, target_type, target_id)
);
