-- ============================================================================
-- VIAJOU — Catálogo de destinos do Brasil e do mundo (dados reais, não é demonstração).
-- Cidades reais com coordenadas públicas e descrições próprias. Pode rodar em qualquer
-- ambiente (inclusive com --sem-demo). Gerado a partir de uma lista; ON CONFLICT mantém
-- o que já existe, então rodar de novo não duplica nada.
-- ============================================================================

INSERT INTO destinations (slug, name, city, state, country, description, latitude, longitude, is_demo, search_key) VALUES
  ('fernando-de-noronha-pe', 'Fernando de Noronha', 'Fernando de Noronha', 'PE', 'Brasil', 'Arquipélago protegido por parque nacional marinho, com mergulho, golfinhos e praias de água transparente.', -3.854700, -32.424700, FALSE, 'fernando de noronha pe brasil'),
  ('arraial-do-cabo-rj', 'Arraial do Cabo', 'Arraial do Cabo', 'RJ', 'Brasil', 'Água fria e muito clara, praias de areia branca e passeios de barco pela costa.', -22.966100, -42.027800, FALSE, 'arraial do cabo rj brasil'),
  ('paraty-rj', 'Paraty', 'Paraty', 'RJ', 'Brasil', 'Centro histórico colonial, ilhas na baía e cachoeiras na serra.', -23.217800, -44.713100, FALSE, 'paraty rj brasil'),
  ('porto-de-galinhas-pe', 'Porto de Galinhas', 'Ipojuca', 'PE', 'Brasil', 'Piscinas naturais nos recifes e praias de água morna no litoral sul de Pernambuco.', -8.502500, -35.005000, FALSE, 'porto de galinhas ipojuca pe brasil'),
  ('lencois-maranhenses-ma', 'Lençóis Maranhenses', 'Barreirinhas', 'MA', 'Brasil', 'Dunas brancas com lagoas de água da chuva, cheias no meio do ano.', -2.753600, -42.826400, FALSE, 'lencois maranhenses barreirinhas ma brasil'),
  ('chapada-das-mesas-ma', 'Chapada das Mesas', 'Carolina', 'MA', 'Brasil', 'Cerrado com chapadões, cachoeiras grandes e poços de água azul.', -7.332500, -47.469700, FALSE, 'chapada das mesas carolina ma brasil'),
  ('foz-do-iguacu-pr', 'Foz do Iguaçu', 'Foz do Iguaçu', 'PR', 'Brasil', 'As Cataratas do Iguaçu, na fronteira com a Argentina, cercadas de mata atlântica.', -25.516300, -54.585400, FALSE, 'foz do iguacu pr brasil'),
  ('bonito-ms', 'Bonito', 'Bonito', 'MS', 'Brasil', 'Rios de água cristalina para flutuação, grutas e cachoeiras.', -21.126100, -56.483600, FALSE, 'bonito ms brasil'),
  ('salvador-ba', 'Salvador', 'Salvador', 'BA', 'Brasil', 'Pelourinho, cultura afro-brasileira, culinária baiana e praias urbanas.', -12.977700, -38.501600, FALSE, 'salvador ba brasil'),
  ('sao-paulo-sp', 'São Paulo', 'São Paulo', 'SP', 'Brasil', 'Maior cidade do país, com museus, vida noturna e gastronomia do mundo todo.', -23.550500, -46.633300, FALSE, 'sao paulo sp brasil'),
  ('santos-sp', 'Santos', 'Santos', 'SP', 'Brasil', 'Orla com o maior jardim de praia do mundo, centro histórico e o porto.', -23.960800, -46.333600, FALSE, 'santos sp brasil'),
  ('campos-do-jordao-sp', 'Campos do Jordão', 'Campos do Jordão', 'SP', 'Brasil', 'Serra da Mantiqueira com clima frio, arquitetura de montanha e fondue.', -22.739400, -45.591400, FALSE, 'campos do jordao sp brasil'),
  ('jericoacoara-ce', 'Jericoacoara', 'Jijoca de Jericoacoara', 'CE', 'Brasil', 'Vila de areia entre dunas e lagoas, famosa pelo pôr do sol e pelo kitesurf.', -2.797500, -40.513700, FALSE, 'jericoacoara jijoca de jericoacoara ce brasil'),
  ('maragogi-al', 'Maragogi', 'Maragogi', 'AL', 'Brasil', 'Piscinas naturais em alto-mar na Costa dos Corais.', -9.012200, -35.222500, FALSE, 'maragogi al brasil'),
  ('chapada-diamantina-ba', 'Chapada Diamantina', 'Lençóis', 'BA', 'Brasil', 'Trilhas longas, cachoeiras e cavernas no interior da Bahia.', -12.563600, -41.389700, FALSE, 'chapada diamantina lencois ba brasil'),
  ('manaus-am', 'Manaus', 'Manaus', 'AM', 'Brasil', 'Porta de entrada da Amazônia, com o Encontro das Águas e hotéis de selva.', -3.119000, -60.021700, FALSE, 'manaus am brasil'),
  ('buenos-aires-ar', 'Buenos Aires', 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Bairros com arquitetura europeia, tango, parrillas e cafés tradicionais.', -34.603700, -58.381600, FALSE, 'buenos aires buenos aires argentina'),
  ('bariloche-ar', 'Bariloche', 'San Carlos de Bariloche', 'Río Negro', 'Argentina', 'Lagos e montanhas da Patagônia, com esqui no inverno e trilhas no verão.', -41.133500, -71.310300, FALSE, 'bariloche san carlos de bariloche rio negro argentina'),
  ('ushuaia-ar', 'Ushuaia', 'Ushuaia', 'Tierra del Fuego', 'Argentina', 'Cidade no extremo sul do continente, com o Canal de Beagle e montanhas nevadas.', -54.801900, -68.303000, FALSE, 'ushuaia tierra del fuego argentina'),
  ('el-calafate-ar', 'El Calafate', 'El Calafate', 'Santa Cruz', 'Argentina', 'Base para o glaciar Perito Moreno, no Parque Nacional Los Glaciares.', -50.337900, -72.264800, FALSE, 'el calafate santa cruz argentina'),
  ('santiago-cl', 'Santiago', 'Santiago', 'Região Metropolitana', 'Chile', 'Capital ao pé dos Andes, com vinícolas por perto e neve no inverno.', -33.448900, -70.669300, FALSE, 'santiago regiao metropolitana chile'),
  ('san-pedro-de-atacama-cl', 'San Pedro de Atacama', 'San Pedro de Atacama', 'Antofagasta', 'Chile', 'Deserto mais seco do mundo, com gêiseres, lagunas e céu para observar estrelas.', -22.908700, -68.199700, FALSE, 'san pedro de atacama antofagasta chile'),
  ('cusco-pe', 'Cusco', 'Cusco', 'Cusco', 'Peru', 'Antiga capital inca e ponto de partida para Machu Picchu e o Vale Sagrado.', -13.532000, -71.967500, FALSE, 'cusco cusco peru'),
  ('lima-pe', 'Lima', 'Lima', 'Lima', 'Peru', 'Capital peruana à beira do Pacífico, referência em gastronomia.', -12.046400, -77.042800, FALSE, 'lima lima peru'),
  ('cartagena-co', 'Cartagena', 'Cartagena', 'Bolívar', 'Colômbia', 'Cidade murada colorida no Caribe colombiano, com ilhas por perto.', 10.391000, -75.479400, FALSE, 'cartagena bolivar colombia'),
  ('montevideu-uy', 'Montevidéu', 'Montevidéu', 'Montevidéu', 'Uruguai', 'Capital tranquila com a longa Rambla à beira do Rio da Prata.', -34.901100, -56.164500, FALSE, 'montevideu montevideu uruguai'),
  ('punta-del-este-uy', 'Punta del Este', 'Punta del Este', 'Maldonado', 'Uruguai', 'Balneário de praias de mar aberto e de águas calmas.', -34.963100, -54.950000, FALSE, 'punta del este maldonado uruguai'),
  ('uyuni-bo', 'Salar de Uyuni', 'Uyuni', 'Potosí', 'Bolívia', 'O maior deserto de sal do mundo, que vira espelho na época de chuvas.', -20.463000, -66.825000, FALSE, 'salar de uyuni uyuni potosi bolivia'),
  ('nova-york-us', 'Nova York', 'Nova York', 'Nova York', 'Estados Unidos', 'Times Square, Central Park, museus e a Estátua da Liberdade.', 40.712800, -74.006000, FALSE, 'nova york nova york estados unidos'),
  ('orlando-us', 'Orlando', 'Orlando', 'Flórida', 'Estados Unidos', 'Parques da Disney, da Universal e muitos outros.', 28.538300, -81.379200, FALSE, 'orlando florida estados unidos'),
  ('miami-us', 'Miami', 'Miami', 'Flórida', 'Estados Unidos', 'Praias, art déco em South Beach e compras.', 25.761700, -80.191800, FALSE, 'miami florida estados unidos'),
  ('las-vegas-us', 'Las Vegas', 'Las Vegas', 'Nevada', 'Estados Unidos', 'Cassinos, shows e acesso a parques nacionais do deserto.', 36.169900, -115.139800, FALSE, 'las vegas nevada estados unidos'),
  ('san-francisco-us', 'San Francisco', 'San Francisco', 'Califórnia', 'Estados Unidos', 'Golden Gate, ladeiras, bondes e vinícolas a pouca distância.', 37.774900, -122.419400, FALSE, 'san francisco california estados unidos'),
  ('los-angeles-us', 'Los Angeles', 'Los Angeles', 'Califórnia', 'Estados Unidos', 'Hollywood, praias como Santa Monica e estúdios de cinema.', 34.052200, -118.243700, FALSE, 'los angeles california estados unidos'),
  ('cancun-mx', 'Cancún', 'Cancún', 'Quintana Roo', 'México', 'Praias do Caribe mexicano, cenotes e ruínas maias.', 21.161900, -86.851500, FALSE, 'cancun quintana roo mexico'),
  ('cidade-do-mexico-mx', 'Cidade do México', 'Cidade do México', 'Cidade do México', 'México', 'Centro histórico, pirâmides de Teotihuacán por perto e comida de rua.', 19.432600, -99.133200, FALSE, 'cidade do mexico cidade do mexico mexico'),
  ('punta-cana-do', 'Punta Cana', 'Punta Cana', 'La Altagracia', 'República Dominicana', 'Resorts e praias de coqueiros no Caribe.', 18.582000, -68.405500, FALSE, 'punta cana la altagracia republica dominicana'),
  ('havana-cu', 'Havana', 'Havana', 'Havana', 'Cuba', 'Centro histórico colonial, carros antigos e música nas ruas.', 23.113600, -82.366600, FALSE, 'havana havana cuba'),
  ('la-fortuna-cr', 'La Fortuna', 'La Fortuna', 'Alajuela', 'Costa Rica', 'Vulcão Arenal, florestas, cachoeiras e águas termais.', 10.467800, -84.642700, FALSE, 'la fortuna alajuela costa rica'),
  ('banff-ca', 'Banff', 'Banff', 'Alberta', 'Canadá', 'Lagos turquesa e picos das Montanhas Rochosas.', 51.178400, -115.570800, FALSE, 'banff alberta canada'),
  ('toronto-ca', 'Toronto', 'Toronto', 'Ontário', 'Canadá', 'Cidade multicultural às margens do Lago Ontário, perto das Cataratas do Niágara.', 43.653200, -79.383200, FALSE, 'toronto ontario canada'),
  ('lisboa-pt', 'Lisboa', 'Lisboa', 'Lisboa', 'Portugal', 'Bairros em colinas, elétricos, miradouros e pastéis de nata.', 38.722300, -9.139300, FALSE, 'lisboa lisboa portugal'),
  ('porto-pt', 'Porto', 'Porto', 'Porto', 'Portugal', 'Ribeira à beira do Douro, azulejos e as caves do vinho do Porto.', 41.157900, -8.629100, FALSE, 'porto porto portugal'),
  ('paris-fr', 'Paris', 'Paris', 'Île-de-France', 'França', 'Torre Eiffel, Louvre, cafés e passeios às margens do Sena.', 48.856600, 2.352200, FALSE, 'paris ile de france franca'),
  ('roma-it', 'Roma', 'Roma', 'Lácio', 'Itália', 'Coliseu, Vaticano, fontes barrocas e massas tradicionais.', 41.902800, 12.496400, FALSE, 'roma lacio italia'),
  ('veneza-it', 'Veneza', 'Veneza', 'Vêneto', 'Itália', 'Cidade sobre a lagoa, com canais, gôndolas e a Praça São Marcos.', 45.440800, 12.315500, FALSE, 'veneza veneto italia'),
  ('florenca-it', 'Florença', 'Florença', 'Toscana', 'Itália', 'Berço do Renascimento, com museus e a Toscana dos vinhos por perto.', 43.769600, 11.255800, FALSE, 'florenca toscana italia'),
  ('costa-amalfitana-it', 'Costa Amalfitana', 'Amalfi', 'Campânia', 'Itália', 'Vilarejos coloridos em penhascos sobre o Mediterrâneo.', 40.634000, 14.602700, FALSE, 'costa amalfitana amalfi campania italia'),
  ('barcelona-es', 'Barcelona', 'Barcelona', 'Catalunha', 'Espanha', 'Obras de Gaudí, bairro gótico, praia urbana e tapas.', 41.387400, 2.168600, FALSE, 'barcelona catalunha espanha'),
  ('madri-es', 'Madri', 'Madri', 'Comunidade de Madri', 'Espanha', 'Grandes museus, Parque do Retiro e vida noturna animada.', 40.416800, -3.703800, FALSE, 'madri comunidade de madri espanha'),
  ('londres-gb', 'Londres', 'Londres', 'Inglaterra', 'Reino Unido', 'Museus gratuitos, palácios, parques e teatros do West End.', 51.507400, -0.127800, FALSE, 'londres inglaterra reino unido'),
  ('amsterda-nl', 'Amsterdã', 'Amsterdã', 'Holanda do Norte', 'Países Baixos', 'Canais, bicicletas e museus como o Rijksmuseum e o de Van Gogh.', 52.367600, 4.904100, FALSE, 'amsterda holanda do norte paises baixos'),
  ('berlim-de', 'Berlim', 'Berlim', 'Berlim', 'Alemanha', 'História do século XX, arte de rua e vida cultural intensa.', 52.520000, 13.405000, FALSE, 'berlim berlim alemanha'),
  ('praga-cz', 'Praga', 'Praga', 'Praga', 'Tchéquia', 'Centro medieval, Ponte Carlos e o castelo sobre a cidade.', 50.075500, 14.437800, FALSE, 'praga praga tchequia'),
  ('zermatt-ch', 'Zermatt', 'Zermatt', 'Valais', 'Suíça', 'Vila sem carros aos pés do Matterhorn, com esqui o ano todo nas geleiras.', 46.020700, 7.749100, FALSE, 'zermatt valais suica'),
  ('interlaken-ch', 'Interlaken', 'Interlaken', 'Berna', 'Suíça', 'Entre dois lagos, base para os Alpes e esportes de aventura.', 46.686300, 7.863200, FALSE, 'interlaken berna suica'),
  ('santorini-gr', 'Santorini', 'Santorini', 'Egeu Meridional', 'Grécia', 'Casas brancas sobre a caldeira de um vulcão e pores do sol famosos.', 36.393200, 25.461500, FALSE, 'santorini egeu meridional grecia'),
  ('atenas-gr', 'Atenas', 'Atenas', 'Ática', 'Grécia', 'Acrópole, Partenon e bairros antigos como Plaka.', 37.983800, 23.727500, FALSE, 'atenas atica grecia'),
  ('dubrovnik-hr', 'Dubrovnik', 'Dubrovnik', 'Dubrovnik-Neretva', 'Croácia', 'Cidade murada no Mar Adriático, com ilhas e praias por perto.', 42.650700, 18.094400, FALSE, 'dubrovnik dubrovnik neretva croacia'),
  ('reykjavik-is', 'Reykjavík', 'Reykjavík', 'Região da Capital', 'Islândia', 'Base para auroras boreais, cachoeiras, gêiseres e geleiras.', 64.146600, -21.942600, FALSE, 'reykjavik regiao da capital islandia'),
  ('rovaniemi-fi', 'Rovaniemi', 'Rovaniemi', 'Lapônia', 'Finlândia', 'Cidade no Círculo Polar Ártico, com neve, auroras e a vila do Papai Noel.', 66.503900, 25.729400, FALSE, 'rovaniemi laponia finlandia'),
  ('istambul-tr', 'Istambul', 'Istambul', 'Istambul', 'Turquia', 'Entre a Europa e a Ásia, com mesquitas, bazares e o Bósforo.', 41.008200, 28.978400, FALSE, 'istambul istambul turquia'),
  ('capadocia-tr', 'Capadócia', 'Göreme', 'Nevşehir', 'Turquia', 'Chaminés de pedra, cidades subterrâneas e voos de balão ao amanhecer.', 38.643100, 34.828900, FALSE, 'capadocia goreme nevsehir turquia'),
  ('cairo-eg', 'Cairo', 'Cairo', 'Cairo', 'Egito', 'Pirâmides de Gizé, Esfinge e o Museu Egípcio.', 30.044400, 31.235700, FALSE, 'cairo cairo egito'),
  ('marrakech-ma', 'Marrakech', 'Marrakech', 'Marrakech-Safi', 'Marrocos', 'Medina com souks, palácios e a praça Jemaa el-Fna.', 31.629500, -7.981100, FALSE, 'marrakech marrakech safi marrocos'),
  ('cidade-do-cabo-za', 'Cidade do Cabo', 'Cidade do Cabo', 'Cabo Ocidental', 'África do Sul', 'Montanha da Mesa, praias, pinguins e vinícolas.', -33.924900, 18.424100, FALSE, 'cidade do cabo cabo ocidental africa do sul'),
  ('zanzibar-tz', 'Zanzibar', 'Stone Town', 'Zanzibar', 'Tanzânia', 'Praias de areia branca e a cidade histórica de Stone Town.', -6.165900, 39.202600, FALSE, 'zanzibar stone town zanzibar tanzania'),
  ('dubai-ae', 'Dubai', 'Dubai', 'Dubai', 'Emirados Árabes Unidos', 'Arranha-céus, compras e passeios pelo deserto.', 25.204800, 55.270800, FALSE, 'dubai dubai emirados arabes unidos'),
  ('petra-jo', 'Petra', 'Wadi Musa', 'Ma''an', 'Jordânia', 'Cidade esculpida na rocha pelos nabateus, perto do deserto de Wadi Rum.', 30.328500, 35.444400, FALSE, 'petra wadi musa ma an jordania'),
  ('toquio-jp', 'Tóquio', 'Tóquio', 'Tóquio', 'Japão', 'Metrópole de bairros muito diferentes, templos e culinária de primeira.', 35.676200, 139.650300, FALSE, 'toquio toquio japao'),
  ('quioto-jp', 'Quioto', 'Quioto', 'Quioto', 'Japão', 'Antiga capital com templos, jardins e o bairro de Gion.', 35.011600, 135.768100, FALSE, 'quioto quioto japao'),
  ('bangkok-th', 'Bangkok', 'Bangkok', 'Bangkok', 'Tailândia', 'Templos dourados, mercados e comida de rua.', 13.756300, 100.501800, FALSE, 'bangkok bangkok tailandia'),
  ('phuket-th', 'Phuket', 'Phuket', 'Phuket', 'Tailândia', 'Maior ilha da Tailândia e base para as ilhas do Mar de Andamão.', 7.880400, 98.392300, FALSE, 'phuket phuket tailandia'),
  ('bali-id', 'Bali', 'Ubud', 'Bali', 'Indonésia', 'Terraços de arroz, templos, cachoeiras e praias de surfe.', -8.506900, 115.262500, FALSE, 'bali ubud bali indonesia'),
  ('singapura-sg', 'Singapura', 'Singapura', 'Singapura', 'Singapura', 'Cidade-estado com jardins futuristas e centros de comida de rua.', 1.352100, 103.819800, FALSE, 'singapura singapura singapura'),
  ('seul-kr', 'Seul', 'Seul', 'Seul', 'Coreia do Sul', 'Palácios antigos, bairros modernos e cultura pop coreana.', 37.566500, 126.978000, FALSE, 'seul seul coreia do sul'),
  ('hanoi-vn', 'Hanói', 'Hanói', 'Hanói', 'Vietnã', 'Bairro antigo de ruas estreitas e porta de entrada para a Baía de Ha Long.', 21.027800, 105.834200, FALSE, 'hanoi hanoi vietna'),
  ('agra-in', 'Agra', 'Agra', 'Uttar Pradesh', 'Índia', 'Cidade do Taj Mahal e do Forte de Agra.', 27.176700, 78.008100, FALSE, 'agra uttar pradesh india'),
  ('maldivas-mv', 'Maldivas', 'Malé', 'Malé', 'Maldivas', 'Atóis no Oceano Índico, com bangalôs sobre a água e mergulho.', 4.175500, 73.509300, FALSE, 'maldivas male male maldivas'),
  ('sydney-au', 'Sydney', 'Sydney', 'Nova Gales do Sul', 'Austrália', 'Opera House, a ponte da baía e praias como Bondi.', -33.868800, 151.209300, FALSE, 'sydney nova gales do sul australia'),
  ('queenstown-nz', 'Queenstown', 'Queenstown', 'Otago', 'Nova Zelândia', 'Capital mundial da aventura, entre lagos e montanhas.', -45.031200, 168.662600, FALSE, 'queenstown otago nova zelandia'),
  ('bora-bora-pf', 'Bora Bora', 'Bora Bora', 'Ilhas de Sotavento', 'Polinésia Francesa', 'Lagoa azul cercada de recifes, aos pés do Monte Otemanu.', -16.500400, -151.741500, FALSE, 'bora bora ilhas de sotavento polinesia francesa')
ON CONFLICT DO NOTHING;

INSERT INTO destination_styles (destination_id, style)
SELECT d.id, v.style
  FROM (VALUES
    ('fernando-de-noronha-pe', 'praia'),
    ('fernando-de-noronha-pe', 'trilha'),
    ('fernando-de-noronha-pe', 'aventura'),
    ('arraial-do-cabo-rj', 'praia'),
    ('arraial-do-cabo-rj', 'trilha'),
    ('paraty-rj', 'historico'),
    ('paraty-rj', 'praia'),
    ('paraty-rj', 'cachoeira'),
    ('paraty-rj', 'gastronomia'),
    ('porto-de-galinhas-pe', 'praia'),
    ('lencois-maranhenses-ma', 'aventura'),
    ('lencois-maranhenses-ma', 'trilha'),
    ('chapada-das-mesas-ma', 'cachoeira'),
    ('chapada-das-mesas-ma', 'trilha'),
    ('chapada-das-mesas-ma', 'aventura'),
    ('foz-do-iguacu-pr', 'cachoeira'),
    ('foz-do-iguacu-pr', 'floresta'),
    ('foz-do-iguacu-pr', 'aventura'),
    ('bonito-ms', 'cachoeira'),
    ('bonito-ms', 'aventura'),
    ('bonito-ms', 'floresta'),
    ('salvador-ba', 'historico'),
    ('salvador-ba', 'praia'),
    ('salvador-ba', 'cidade'),
    ('salvador-ba', 'gastronomia'),
    ('sao-paulo-sp', 'cidade'),
    ('sao-paulo-sp', 'gastronomia'),
    ('santos-sp', 'praia'),
    ('santos-sp', 'cidade'),
    ('santos-sp', 'historico'),
    ('campos-do-jordao-sp', 'frio'),
    ('campos-do-jordao-sp', 'montanha'),
    ('campos-do-jordao-sp', 'gastronomia'),
    ('jericoacoara-ce', 'praia'),
    ('jericoacoara-ce', 'aventura'),
    ('maragogi-al', 'praia'),
    ('chapada-diamantina-ba', 'trilha'),
    ('chapada-diamantina-ba', 'cachoeira'),
    ('chapada-diamantina-ba', 'montanha'),
    ('manaus-am', 'floresta'),
    ('manaus-am', 'aventura'),
    ('buenos-aires-ar', 'cidade'),
    ('buenos-aires-ar', 'gastronomia'),
    ('buenos-aires-ar', 'historico'),
    ('bariloche-ar', 'frio'),
    ('bariloche-ar', 'montanha'),
    ('bariloche-ar', 'trilha'),
    ('ushuaia-ar', 'frio'),
    ('ushuaia-ar', 'montanha'),
    ('ushuaia-ar', 'aventura'),
    ('el-calafate-ar', 'frio'),
    ('el-calafate-ar', 'montanha'),
    ('el-calafate-ar', 'trilha'),
    ('santiago-cl', 'cidade'),
    ('santiago-cl', 'montanha'),
    ('santiago-cl', 'gastronomia'),
    ('santiago-cl', 'frio'),
    ('san-pedro-de-atacama-cl', 'aventura'),
    ('san-pedro-de-atacama-cl', 'trilha'),
    ('cusco-pe', 'historico'),
    ('cusco-pe', 'montanha'),
    ('cusco-pe', 'trilha'),
    ('lima-pe', 'gastronomia'),
    ('lima-pe', 'cidade'),
    ('cartagena-co', 'historico'),
    ('cartagena-co', 'praia'),
    ('montevideu-uy', 'cidade'),
    ('montevideu-uy', 'gastronomia'),
    ('punta-del-este-uy', 'praia'),
    ('uyuni-bo', 'aventura'),
    ('nova-york-us', 'cidade'),
    ('nova-york-us', 'gastronomia'),
    ('orlando-us', 'aventura'),
    ('orlando-us', 'cidade'),
    ('miami-us', 'praia'),
    ('miami-us', 'cidade'),
    ('las-vegas-us', 'cidade'),
    ('las-vegas-us', 'aventura'),
    ('san-francisco-us', 'cidade'),
    ('san-francisco-us', 'gastronomia'),
    ('los-angeles-us', 'cidade'),
    ('los-angeles-us', 'praia'),
    ('cancun-mx', 'praia'),
    ('cancun-mx', 'historico'),
    ('cancun-mx', 'aventura'),
    ('cidade-do-mexico-mx', 'cidade'),
    ('cidade-do-mexico-mx', 'historico'),
    ('cidade-do-mexico-mx', 'gastronomia'),
    ('punta-cana-do', 'praia'),
    ('havana-cu', 'historico'),
    ('havana-cu', 'cidade'),
    ('la-fortuna-cr', 'floresta'),
    ('la-fortuna-cr', 'aventura'),
    ('la-fortuna-cr', 'cachoeira'),
    ('banff-ca', 'montanha'),
    ('banff-ca', 'trilha'),
    ('banff-ca', 'floresta'),
    ('banff-ca', 'frio'),
    ('toronto-ca', 'cidade'),
    ('toronto-ca', 'cachoeira'),
    ('lisboa-pt', 'cidade'),
    ('lisboa-pt', 'historico'),
    ('lisboa-pt', 'gastronomia'),
    ('porto-pt', 'cidade'),
    ('porto-pt', 'historico'),
    ('porto-pt', 'gastronomia'),
    ('paris-fr', 'cidade'),
    ('paris-fr', 'historico'),
    ('paris-fr', 'gastronomia'),
    ('roma-it', 'historico'),
    ('roma-it', 'cidade'),
    ('roma-it', 'gastronomia'),
    ('veneza-it', 'historico'),
    ('veneza-it', 'cidade'),
    ('florenca-it', 'historico'),
    ('florenca-it', 'gastronomia'),
    ('costa-amalfitana-it', 'praia'),
    ('costa-amalfitana-it', 'gastronomia'),
    ('barcelona-es', 'cidade'),
    ('barcelona-es', 'praia'),
    ('barcelona-es', 'historico'),
    ('barcelona-es', 'gastronomia'),
    ('madri-es', 'cidade'),
    ('madri-es', 'historico'),
    ('madri-es', 'gastronomia'),
    ('londres-gb', 'cidade'),
    ('londres-gb', 'historico'),
    ('amsterda-nl', 'cidade'),
    ('amsterda-nl', 'historico'),
    ('berlim-de', 'cidade'),
    ('berlim-de', 'historico'),
    ('praga-cz', 'historico'),
    ('praga-cz', 'cidade'),
    ('zermatt-ch', 'frio'),
    ('zermatt-ch', 'montanha'),
    ('zermatt-ch', 'trilha'),
    ('interlaken-ch', 'montanha'),
    ('interlaken-ch', 'aventura'),
    ('interlaken-ch', 'trilha'),
    ('santorini-gr', 'praia'),
    ('atenas-gr', 'historico'),
    ('atenas-gr', 'cidade'),
    ('dubrovnik-hr', 'historico'),
    ('dubrovnik-hr', 'praia'),
    ('reykjavik-is', 'frio'),
    ('reykjavik-is', 'aventura'),
    ('reykjavik-is', 'cachoeira'),
    ('rovaniemi-fi', 'frio'),
    ('rovaniemi-fi', 'aventura'),
    ('rovaniemi-fi', 'floresta'),
    ('istambul-tr', 'historico'),
    ('istambul-tr', 'cidade'),
    ('istambul-tr', 'gastronomia'),
    ('capadocia-tr', 'aventura'),
    ('capadocia-tr', 'historico'),
    ('capadocia-tr', 'trilha'),
    ('cairo-eg', 'historico'),
    ('cairo-eg', 'cidade'),
    ('marrakech-ma', 'historico'),
    ('marrakech-ma', 'gastronomia'),
    ('cidade-do-cabo-za', 'montanha'),
    ('cidade-do-cabo-za', 'praia'),
    ('cidade-do-cabo-za', 'gastronomia'),
    ('zanzibar-tz', 'praia'),
    ('zanzibar-tz', 'historico'),
    ('dubai-ae', 'cidade'),
    ('dubai-ae', 'aventura'),
    ('petra-jo', 'historico'),
    ('petra-jo', 'aventura'),
    ('petra-jo', 'trilha'),
    ('toquio-jp', 'cidade'),
    ('toquio-jp', 'gastronomia'),
    ('quioto-jp', 'historico'),
    ('quioto-jp', 'cidade'),
    ('bangkok-th', 'cidade'),
    ('bangkok-th', 'historico'),
    ('bangkok-th', 'gastronomia'),
    ('phuket-th', 'praia'),
    ('bali-id', 'praia'),
    ('bali-id', 'floresta'),
    ('bali-id', 'cachoeira'),
    ('singapura-sg', 'cidade'),
    ('singapura-sg', 'gastronomia'),
    ('seul-kr', 'cidade'),
    ('seul-kr', 'gastronomia'),
    ('hanoi-vn', 'historico'),
    ('hanoi-vn', 'gastronomia'),
    ('hanoi-vn', 'cidade'),
    ('agra-in', 'historico'),
    ('maldivas-mv', 'praia'),
    ('sydney-au', 'cidade'),
    ('sydney-au', 'praia'),
    ('queenstown-nz', 'aventura'),
    ('queenstown-nz', 'montanha'),
    ('queenstown-nz', 'frio'),
    ('bora-bora-pf', 'praia')
  ) AS v(dest_slug, style)
  JOIN destinations d ON d.slug = v.dest_slug
ON CONFLICT DO NOTHING;
